# Generated by Django 5.2.4 on 2025-07-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cargo', models.CharField(choices=[('GER', 'Gerente'), ('CORD', 'Cordernador'), ('SUP', 'Supervisor'), ('OPR', 'Operador'), ('AUX', 'Auxiliar')], max_length=6)),
                ('area', models.CharField(max_length=50)),
                ('material_app', models.BooleanField(default=False)),
            ],
        ),
    ]
