# Generated by Django 5.2.4 on 2025-07-10 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('GER', 'Gerente'), ('CORD', 'Coordenador'), ('SUP', 'Supervisor'), ('OPR', 'Operador'), ('AUX', 'Auxiliar')], max_length=6),
        ),
    ]
