# Generated by Django 5.2.4 on 2025-07-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_colaborador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='departamento',
            field=models.CharField(choices=[('ADM', 'Administrativo'), ('PROD', 'Produção'), ('RH', 'Recursos Humanos'), ('TI', 'Tecnologia da Informação'), ('FIN', 'Financeiro')], default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
