# Generated by Django 5.2.4 on 2025-07-11 00:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_colaborador_data_admissao_colaborador_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='telefone',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(default=1, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve estar no formato: 000.000.000-00', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
            preserve_default=False,
        ),
    ]
