# Generated by Django 5.2.4 on 2025-07-11 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_colaborador_telefone_colaborador_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='material_app',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='area',
            field=models.CharField(choices=[('OP', 'Operações'), ('ARM', 'Armazém'), ('MAT', 'Materiais'), ('MANU', 'Manutenção')], max_length=6),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cargo',
            field=models.CharField(choices=[('GER', 'Gerente'), ('CORD', 'Coordenador'), ('SUP', 'Supervisor'), ('OPR1', 'Operador I'), ('OPR2', 'Operador II'), ('AUX', 'Auxiliar')], max_length=6),
        ),
    ]
