# Generated by Django 5.2.4 on 2025-07-11 13:27

import django.utils.timezone
import estoque.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_remove_colaborador_data_admissao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('registro', models.AutoField(primary_key=True, serialize=False)),
                ('equipamento', models.CharField(max_length=100)),
                ('identificador', models.CharField(max_length=50)),
                ('caracteristica', models.TextField(blank=True, null=True)),
                ('descricao_uso', models.TextField(blank=True, null=True)),
                ('tipo_equipamento', models.CharField(choices=[('ELETRICO', 'Elétrico'), ('MANUAL', 'Manual'), ('HIDRAULICO', 'Hidráulico'), ('PNEUMATICO', 'Pneumático'), ('OUTRO', 'Outro')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('localizacao', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=estoque.models.caminho_foto)),
                ('qrcode', models.ImageField(blank=True, upload_to=estoque.models.caminho_qrcode)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
