# Generated by Django 5.2.4 on 2025-07-11 19:29

import estoque.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='anexo_certificacao',
            field=models.FileField(blank=True, null=True, upload_to=estoque.models.caminho_anexo),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='codigo_certificado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_certificacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='detalhes_certificacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='empresa_certificacao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
