# Generated by Django 5.2.4 on 2025-07-12 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_anexocertificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_certificado', models.CharField(max_length=100)),
                ('data_certificacao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('empresa_certificadora', models.CharField(max_length=100)),
                ('codigo_certificado', models.CharField(max_length=50)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('anexo', models.FileField(blank=True, null=True, upload_to='certificacoes/')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='estoque.equipamento')),
            ],
        ),
    ]
