# Generated by Django 5.2.4 on 2025-07-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_certificacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnexoCertificacao',
        ),
    ]
