# Generated by Django 5.2.4 on 2025-07-12 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_delete_anexocertificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='anexo_certificacao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='codigo_certificado',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='data_certificacao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='detalhes_certificacao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='empresa_certificacao',
        ),
    ]
