# Generated by Django 5.2.4 on 2025-07-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_agendamento_pecaagendada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='local_uso',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='matricula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='numero_agendamento',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
