# Generated by Django 5.2.4 on 2025-07-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0014_alter_agendamento_local_uso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='setor_solicitante',
            field=models.CharField(choices=[('OPERACOES', 'Operações'), ('ARMAZEM', 'Armazém'), ('MANUTENCAO', 'Manutenção'), ('TERMINAL2', 'Terminal 2')], default='OPERACOES', max_length=100),
        ),
    ]
