# Generated by Django 5.2.4 on 2025-07-15 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_alter_agendamento_setor_solicitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('termo_assinado', models.FileField(blank=True, null=True, upload_to='termos_saida/%Y/%m/%d/')),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='saida_material', to='estoque.agendamento')),
                ('responsavel_entrega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_realizadas', to='estoque.colaborador')),
            ],
            options={
                'verbose_name': 'Saída de Material',
                'verbose_name_plural': 'Saídas de Materiais',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='VerificacaoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_avaria', models.BooleanField(default=False)),
                ('na_validade', models.BooleanField(default=True)),
                ('tem_certificacao', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True)),
                ('foto_avaria', models.ImageField(blank=True, null=True, upload_to='avarias/%Y/%m/%d/')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verificacoes', to='estoque.pecaagendada')),
                ('saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verificacoes', to='estoque.saidamaterial')),
            ],
            options={
                'verbose_name': 'Verificação de Peça',
                'verbose_name_plural': 'Verificações de Peças',
            },
        ),
    ]
