# Generated by Django 5.2.4 on 2025-07-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0016_saidamaterial_verificacaopeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('AG', 'Agendado'), ('RT', 'Retirado'), ('DV', 'Devolvido'), ('CN', 'Cancelado')], default='AG', max_length=2),
        ),
    ]
