# Generated by Django 5.2.4 on 2025-07-17 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_agendamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alguma_avaria', models.BooleanField(default=False)),
                ('validade_ok', models.BooleanField(default=False)),
                ('certificacao_ok', models.BooleanField(default=False)),
                ('saida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='estoque.saidamaterial')),
            ],
        ),
        migrations.CreateModel(
            name='TermoRetirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido', models.BooleanField(default=False)),
                ('assinatura_base64', models.TextField(blank=True)),
                ('saida', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termo', to='estoque.saidamaterial')),
            ],
        ),
    ]
