# Generated by Django 5.2.4 on 2025-07-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0018_checklistsaida_termoretirada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidamaterial',
            name='responsavel_entrega',
        ),
        migrations.AddField(
            model_name='saidamaterial',
            name='matricula_responsavel',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saidamaterial',
            name='nome_responsavel',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
