# Generated by Django 5.2.4 on 2025-07-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0019_remove_saidamaterial_responsavel_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidamaterial',
            name='matricula_responsavel',
        ),
        migrations.RemoveField(
            model_name='saidamaterial',
            name='nome_responsavel',
        ),
    ]
