# Generated by Django 5.2.4 on 2025-07-21 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0020_remove_saidamaterial_matricula_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucaoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateTimeField(auto_now_add=True)),
                ('quantidade_devolvida', models.BooleanField(default=True, verbose_name='Quantidade devolvida completa')),
                ('material_com_avaria', models.BooleanField(default=False, verbose_name='Material com avaria')),
                ('observacoes', models.TextField(blank=True)),
                ('saida', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='devolucao', to='estoque.saidamaterial')),
            ],
            options={
                'verbose_name': 'Devolução de Material',
                'verbose_name_plural': 'Devoluções de Materiais',
                'ordering': ['-data_devolucao'],
            },
        ),
    ]
