# Generated by Django 5.2.4 on 2025-07-23 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0021_devolucaomaterial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inventario', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('danificado', models.BooleanField(default=False)),
                ('falta', models.BooleanField(default=False)),
                ('fora_validade', models.BooleanField(default=False)),
                ('observacao', models.TextField(blank=True)),
                ('validado', models.BooleanField(default=False)),
                ('data_validacao', models.DateTimeField(blank=True, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.equipamento')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_validados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
