# Generated by Django 5.2.4 on 2025-07-23 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0022_inventarioequipamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='estoque.equipamento'),
        ),
    ]
