# Generated by Django 5.2.4 on 2025-07-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_alter_colaborador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioequipamento',
            name='data_validacao',
        ),
        migrations.RemoveField(
            model_name='inventarioequipamento',
            name='validado',
        ),
        migrations.RemoveField(
            model_name='inventarioequipamento',
            name='validado_por',
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
    ]
