# Generated by Django 5.2.4 on 2025-07-26 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0026_rename_danificado_inventarioequipamento_descarte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventarioequipamento',
            old_name='descarte',
            new_name='avaria',
        ),
        migrations.RenameField(
            model_name='inventarioequipamento',
            old_name='fora_validade',
            new_name='nao_devolvido',
        ),
    ]
