# Generated by Django 5.2.4 on 2025-07-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0028_equipamento_data_descarte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('DESCARTADO', 'Descartado'), ('MANUTENCAO', 'Em Manutenção')], default='ATIVO', max_length=10),
        ),
    ]
