# Generated by Django 5.2.4 on 2025-07-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0030_notificacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
    ]
