# Generated by Django 5.2.4 on 2025-07-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0031_alter_notificacao_options_alter_notificacao_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={},
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='url',
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('AGENDAMENTO', 'Agendamento'), ('INVENTARIO', 'Inventário')], max_length=20),
        ),
    ]
