# Generated by Django 5.2.4 on 2025-07-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0032_alter_notificacao_options_remove_notificacao_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='url',
            field=models.CharField(blank=True, default='#', max_length=200),
        ),
    ]
