# Generated by Django 5.2.4 on 2025-07-28 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0033_notificacao_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='url',
        ),
    ]
