# Generated by Django 5.2.4 on 2025-07-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0034_remove_notificacao_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'ordering': ['-criado_em']},
        ),
        migrations.AddField(
            model_name='notificacao',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('AGENDAMENTO', 'Agendamento'), ('INVENTARIO', 'Inventário'), ('ALERTA', 'Alerta')], max_length=20),
        ),
    ]
